/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import entities.AssertElement;
import entities.Mouse;
import entities.Scenario;
import entities.TestSuite;
import entities.Visit;
import entities.WaitFor;
import javax.swing.event.TreeSelectionEvent;
import javax.swing.event.TreeSelectionListener;
import model.TestSuiteTreeModel;

/**
 *
 * @author Hyungin Choi
 */
public class MainGUI extends javax.swing.JFrame {

    /**
     * Creates new form MainGUI
     *
     * @param title
     */
    public MainGUI(String title) throws InstantiationException {
        initComponents();
        initFeatureTree();
        this.setTitle(title);

    }

    private void initFeatureTree() throws InstantiationException {
        trFeature.setModel(new TestSuiteTreeModel(prepareTree()));

        trFeature.addTreeSelectionListener(new TreeSelectionListener() {
            public void valueChanged(TreeSelectionEvent e) {
                showDetailsPanel(trFeature.getLastSelectedPathComponent());
            }
        });
    }

    private void showDetailsPanel(Object node) {
        if (node instanceof Visit) {
            VisitGUI visit = new VisitGUI((Visit) node);
            spDetails.setViewportView(visit);
        }
        if (node instanceof Scenario) {
            ScenarioGUI scenario = new ScenarioGUI((Scenario) node);
            spDetails.setViewportView(scenario);
        }
        if (node instanceof AssertElement) {
            AssertGUI assertGUI = new AssertGUI((AssertElement) node);
            spDetails.setViewportView(assertGUI);
        }
        if (node instanceof Mouse) {
            MouseGUI mouse = new MouseGUI((Mouse) node);
            spDetails.setViewportView(mouse);
        }
        if (node instanceof WaitFor) {
            WaitForGUI wf = new WaitForGUI((WaitFor) node);
            spDetails.setViewportView(wf);
        }
    }

    private TestSuite prepareTree() throws InstantiationException {
        TestSuite ts = new TestSuite("first test suite");
        for (int i = 0; i < 5; i++) {
            Scenario sc = new Scenario("Scenario " + i);
            for (int j = 0; j < 2; j++) {
                Visit vs = new Visit();
                sc.addNewCase(vs);
                AssertElement ae = new AssertElement("Element", true, true, "Attribute", true, "is not", "Value", "is", null, "visible", "-", "");
                sc.addNewCase(ae);
                Mouse m = new Mouse("this is target");
                sc.addNewCase(m);
                WaitFor wf = new WaitFor("Element", true, true, "Attribute", true, "is not", "Value", "is", null, "visible", "-", "");
                sc.addNewCase(wf);
                WaitFor wf2 = new WaitFor(5, true);
                sc.addNewCase(wf2);
            }
            ts.addScenario(sc);
        }
        return ts;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblFeatureName = new javax.swing.JLabel();
        spFeature = new javax.swing.JScrollPane();
        trFeature = new javax.swing.JTree();
        spDetails = new javax.swing.JScrollPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblFeatureName.setText("Feature: ");
        lblFeatureName.setName(""); // NOI18N

        spFeature.setPreferredSize(new java.awt.Dimension(2, 2));

        trFeature.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        trFeature.setMaximumSize(new java.awt.Dimension(1000, 1000));
        trFeature.setName(""); // NOI18N
        trFeature.setPreferredSize(new java.awt.Dimension(1000, 64));
        spFeature.setViewportView(trFeature);

        jMenu1.setText("File");
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addComponent(lblFeatureName)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addComponent(spFeature, javax.swing.GroupLayout.PREFERRED_SIZE, 314, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(spDetails, javax.swing.GroupLayout.DEFAULT_SIZE, 665, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblFeatureName)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(spDetails, javax.swing.GroupLayout.DEFAULT_SIZE, 438, Short.MAX_VALUE)
                    .addComponent(spFeature, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(24, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JLabel lblFeatureName;
    private javax.swing.JScrollPane spDetails;
    private javax.swing.JScrollPane spFeature;
    private javax.swing.JTree trFeature;
    // End of variables declaration//GEN-END:variables
}
