/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import entities.Visit;

/**
 *
 * @author Hyungin Choi
 */
public class VisitGUI extends javax.swing.JPanel {

    /**
     * Creates new form VisitGUI
     */
    public VisitGUI(Visit visit) {
        initComponents();
        this.visit = visit;
        prepareGui(visit);
        lblActionGUI.setText(visit.toString());
    }

    private void prepareGui(Visit visit) {
        if (visit.isIsHomepage()) {
            rdHomepage.setSelected(true);
            inactiveLinkText();
            inactiveUrl();
        }
        if (visit.getLinkText() != null && !"".equals(visit.getLinkText())) {
            rdLinkText.setSelected(true);
            txtLinkText.setEnabled(true);
            txtLinkText.setText(visit.getLinkText());
            inactiveUrl();
        }
        if (visit.getUrl() != null && !"".equals(visit.getUrl())) {
            rdUrl.setSelected(true);
            txtUrl.setEnabled(true);
            txtUrl.setText(visit.getUrl());
            inactiveLinkText();
        }
        if (visit.isIsNewWindow()) {
            cbNewWindow.setSelected(true);
        } else {
            cbNewWindow.setSelected(false);
        }
    }

    private void inactiveUrl() {
        txtUrl.setText("");
        txtUrl.setEnabled(false);
    }

    private void inactiveLinkText() {
        txtLinkText.setText("");
        txtLinkText.setEnabled(false);
    }

    private void save() {
        if (rdHomepage.isSelected()) {
            visit.setIsHomepage(true);
            visit.setUrl(null);
            visit.setLinkText(null);
        }
        if (rdLinkText.isSelected()) {
            visit.setLinkText(txtLinkText.getText());
            visit.setUrl(null);
            visit.setIsHomepage(false);
        }
        if (rdUrl.isSelected()) {
            visit.setUrl(txtUrl.getText());
            visit.setLinkText(null);
            visit.setIsHomepage(false);
        }
        if (cbNewWindow.isSelected()) {
            visit.setIsNewWindow(true);
        } else {
            visit.setIsNewWindow(false);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnGroup = new javax.swing.ButtonGroup();
        lblActionGUI = new javax.swing.JLabel();
        txtUrl = new javax.swing.JTextField();
        rdUrl = new javax.swing.JRadioButton();
        rdLinkText = new javax.swing.JRadioButton();
        txtLinkText = new javax.swing.JTextField();
        cbNewWindow = new javax.swing.JCheckBox();
        btnSave = new javax.swing.JButton();
        btnCancel = new javax.swing.JButton();
        rdHomepage = new javax.swing.JRadioButton();

        lblActionGUI.setText("Visit");

        btnGroup.add(rdUrl);
        rdUrl.setText("URL");
        rdUrl.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                rdUrlStateChanged(evt);
            }
        });
        rdUrl.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                rdUrlPropertyChange(evt);
            }
        });

        btnGroup.add(rdLinkText);
        rdLinkText.setText("Link Text");
        rdLinkText.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                rdLinkTextStateChanged(evt);
            }
        });

        cbNewWindow.setText("in New Window");

        btnSave.setText("Save");
        btnSave.setToolTipText("");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        btnCancel.setText("Cancel");
        btnCancel.setToolTipText("");

        btnGroup.add(rdHomepage);
        rdHomepage.setText("Homepage");
        rdHomepage.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                rdHomepageStateChanged(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(rdLinkText)
                                    .addComponent(rdUrl))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtUrl)
                                    .addComponent(txtLinkText, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 253, Short.MAX_VALUE)))
                            .addComponent(rdHomepage)
                            .addComponent(cbNewWindow)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(171, 171, 171)
                        .addComponent(btnCancel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnSave, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblActionGUI, javax.swing.GroupLayout.PREFERRED_SIZE, 383, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblActionGUI)
                .addGap(23, 23, 23)
                .addComponent(rdHomepage)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtUrl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rdUrl))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rdLinkText)
                    .addComponent(txtLinkText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addComponent(cbNewWindow)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCancel)
                    .addComponent(btnSave))
                .addContainerGap(81, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void rdUrlStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_rdUrlStateChanged
        // TODO add your handling code here:
        if (rdUrl.isSelected()) {
            txtUrl.setEnabled(true);
            inactiveLinkText();
        }
    }//GEN-LAST:event_rdUrlStateChanged

    private void rdLinkTextStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_rdLinkTextStateChanged
        // TODO add your handling code here:
        if (rdLinkText.isSelected()) {
            txtLinkText.setEnabled(true);
            inactiveUrl();
        }
    }//GEN-LAST:event_rdLinkTextStateChanged

    private void rdHomepageStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_rdHomepageStateChanged
        // TODO add your handling code here:
        if (rdHomepage.isSelected()) {
            inactiveLinkText();
            inactiveUrl();
        }
    }//GEN-LAST:event_rdHomepageStateChanged

    private void rdUrlPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_rdUrlPropertyChange
        // TODO add your handling code here:
    }//GEN-LAST:event_rdUrlPropertyChange

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        // TODO add your handling code here:
        save();
        lblActionGUI.setText(visit.toString());
    }//GEN-LAST:event_btnSaveActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancel;
    private javax.swing.ButtonGroup btnGroup;
    private javax.swing.JButton btnSave;
    private javax.swing.JCheckBox cbNewWindow;
    private javax.swing.JLabel lblActionGUI;
    private javax.swing.JRadioButton rdHomepage;
    private javax.swing.JRadioButton rdLinkText;
    private javax.swing.JRadioButton rdUrl;
    private javax.swing.JTextField txtLinkText;
    private javax.swing.JTextField txtUrl;
    // End of variables declaration//GEN-END:variables
    private Visit visit;
}
